### ISSUE TITLE
Ruby Capstone (Group Project)

### ISSUE THREAD

**Issue by VitorGuedesMadeira** [VitorGuedesMadeira/Capstone-Ruby#25]
### **Kanban Board**
- click here for [Repository link](https://github.com/VitorGuedesMadeira/Capstone-Ruby) ✅ 
- click here for [Kanban Board link](https://github.com/VitorGuedesMadeira/Capstone-Ruby/projects/1) ☑️ 

**_co-authors(3):_**
- Muhammad Ashraf #2
- Vitor Guedes #8
- Diego Yon #19

**_optional included:_**
- #14

**Comment by Nemwel-Boniface** [comment]
## Hello @VitorGuedesMadeira , @for-ashraf  and @diegoyon         :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
